# SPDX-FileCopyrightText: 2022 Ioan Bizău
# SPDX-FileCopyrightText: 2022 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Social
  name: Usocial
  version: 0.1.6
  tagline: Read. Listen. Pay back.
  description: The minimalist self-hosted feed reader and podcast client for your
    personal server. With Lightning Network support.
  developers:
    Ioan Bizău: http://usocial.me
  dependencies:
    - lnd
  repo: https://github.com/ibz/usocial
  support: https://github.com/ibz/usocial/issues
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - name: main
    image: ghcr.io/ibz/usocial:v0.1.6-buster@sha256:c4ad3524a0eaccf505f3e477ab8ac2eb4e79ddca7f4266e4af0afd49caba389a
    restart: on-failure
    stop_grace_period: 1m
    port: 5000
    data:
      - data:/instance
    environment:
      USOCIAL_JOB: WEB
      APP_PASSWORD: ${APP_SEED}
      LND_IP: ${LND_IP}
      LND_GRPC_PORT: ${LND_GRPC_PORT}
      LND_DIR: /lnd
  - name: fetcher
    depends_on:
      - main
    image: ghcr.io/ibz/usocial:v0.1.4-buster@sha256:a74b562b974bcafca4c5ab15e1a41c269709a9f7e09154c9b66685e9d84ec6af
    restart: on-failure
    stop_grace_period: 1m
    data:
      - data:/instance
    environment:
      USOCIAL_JOB: FETCH_FEEDS
