# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Payments
  name: BitcartCC
  version: 0.6.9.0
  tagline: BitcartCC is a self-hosted payment processor and developer solutions
    platform for cryptocurrencies
  description: BitcartCC provides light-weight, but secure and easy-to-use
    solutions for merchants and developers
  developers:
    BitcartCC: https://bitcartcc.com
  repo: https://github.com/bitcartcc/bitcart
  support: https://bitcartcc.com/#community
  gallery:
    - 1.png
    - 2.png
    - 3.png
  dependencies:
    - electrum
containers:
  - name: admin
    restart: unless-stopped
    image: bitcartcc/bitcart-admin:stable
    command: yarn start
    environment:
      BITCART_ADMIN_LOG_FILE: bitcart.log
      BITCART_ADMIN_API_URL: http://$APP_DOMAIN:$APP_BITCARTCC_MAIN_PORT/api
      BITCART_ADMIN_ROOTPATH: /admin
      BITCART_ADMIN_SOCKS_PROXY: socks5h://$TOR_PROXY_IP:$TOR_PROXY_PORT
      BITCART_ADMIN_ONION_API_URL: http://$APP_HIDDEN_SERVICE/api
      BITCART_ADMIN_ONION_HOST: http://$APP_HIDDEN_SERVICE
  - name: backend
    depends_on:
      - bitcoin
      - database
      - redis
    restart: unless-stopped
    image: bitcartcc/bitcart:stable
    command: bash -c "alembic upgrade head && gunicorn -c gunicorn.conf.py main:app"
    environment:
      IN_DOCKER: false
      LOG_FILE: bitcart.log
      BITCART_DATADIR: /datadir
      BITCART_BACKUPS_DIR: /backups
      BITCART_VOLUMES: /datadir /backups
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      REDIS_HOST: redis://$APP_BITCARTCC_REDIS_IP
      DB_HOST: $APP_BITCARTCC_DATABASE_IP
      BTC_HOST: $APP_BITCARTCC_BITCOIN_IP
      BITCART_BACKEND_ROOTPATH: /api
    data:
      - data/bitcart:/datadir
      - data/backups:/backups
  - name: bitcoin
    restart: unless-stopped
    image: bitcartcc/bitcart-btc:stable
    environment:
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      IN_DOCKER: false
      BTC_SERVER: $ELECTRUM_IP:$ELECTRUM_PORT:t
    data:
      - data/bitcoin:/data
  - name: database
    restart: unless-stopped
    image: ghcr.io/runcitadel/postgres:main@sha256:8f25afe966a63fd3f11a1052e73f30b9de5ddc0876bebaaf944d485374c73c01
    environment:
      POSTGRES_DB: bitcart
      POSTGRES_HOST_AUTH_METHOD: trust
    data:
      - data/postgres:/var/lib/postgresql/data
    user: 1000:1000
  - name: redis
    restart: unless-stopped
    image: redis:alpine
  - name: store
    restart: unless-stopped
    image: bitcartcc/bitcart-store:stable
    command: yarn start
    environment:
      BITCART_STORE_API_URL: http://$APP_DOMAIN:$APP_BITCARTCC_MAIN_PORT/api
      BITCART_STORE_SOCKS_PROXY: socks5h://$TOR_PROXY_IP:$TOR_PROXY_PORT
      BITCART_STORE_ONION_API_URL: http://$APP_HIDDEN_SERVICE/api
      BITCART_STORE_ONION_HOST: http://$APP_HIDDEN_SERVICE
    user: 1000:1000
  - name: worker
    depends_on:
      - backend
    restart: unless-stopped
    image: bitcartcc/bitcart:stable
    command: python3 worker.py
    environment:
      IN_DOCKER: false
      LOG_FILE: bitcart.log
      BITCART_DATADIR: /datadir
      BITCART_BACKUPS_DIR: /backups
      BITCART_VOLUMES: /datadir /backups
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      REDIS_HOST: redis://$APP_BITCARTCC_REDIS_IP
      DB_HOST: $APP_BITCARTCC_DATABASE_IP
      BTC_HOST: $APP_BITCARTCC_BITCOIN_IP
    data:
      - data/bitcart:/datadir
      - data/backups:/backups
  - image: nginx:1.21.3-alpine@sha256:1ff1364a1c4332341fc0a854820f1d50e90e11bb0b93eb53b47dc5e10c680116
    init: true
    port: 80
    name: main
    data:
      - nginx/nginx.conf:/etc/nginx/nginx.conf
