# SPDX-FileCopyrightText: 2022 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v2.json

version: 2
metadata:
  category: Social
  name: Synapse
  version: 1.55.0
  tagline: Matrix homeserver
  description: Description is coming soon.
  developer: Matrix
  website: https://matrix.org
  dependencies: []
  repo: https://github.com/matrix-org/synapse
  support: https://matrix.to/#/#synapse:matrix.org
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  torOnly: false
containers:
  - image: matrixdotorg/synapse:v1.55.0@sha256:4b750f7a4d0ddb9d1b20838e4005b885017e2a317aa3654821de5251b37ef485
    entrypoint: bash
    command: -c './start.py generate && ./start.py migrate_config && exec ./start.py'
    port: 8008
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_HTTP_PORT: 8008
      SYNAPSE_SERVER_NAME: ${APP_HIDDEN_SERVICE}
      SYNAPSE_REPORT_STATS: yes
      SYNAPSE_ENABLE_REGISTRATION: yes
      SYNAPSE_NO_TLS: yes
    name: server
    data:
      - data/synapse:/data
    hiddenServicePorts:
      - 80
      - 8008
