citadel_version: 4
metadata:
  name: Synapse
  version: 1.93.0
  category: Social
  tagline: Matrix homeserver
  developers:
    Matrix: https://matrix.org
  description: Description is coming soon.
  permissions: []
  repo:
    Public: https://github.com/matrix-org/synapse
  support: https://matrix.to/#/#synapse:matrix.org
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: null
  torOnly: false
  compatible: false
services:
  server:
    image: ghcr.io/runcitadel/synapse:develop@sha256:80e15d6247e30d162758178aeb41bb9181e5d7ec9d73af35939bccbb3aecbab9
    entrypoint: bash
    command: -c './start.py generate && ./start.py migrate_config && exec ./start.py'
    environment:
      SYNAPSE_ENABLE_REGISTRATION: yes
      UID: '1000'
      SYNAPSE_REPORT_STATS: yes
      SYNAPSE_SERVER_NAME: ${APP_HIDDEN_SERVICE}
      GID: '1000'
      SYNAPSE_NO_TLS: yes
      SYNAPSE_HTTP_PORT: 8008
    port: 8008
    mounts:
      data:
        data/synapse: /data
    hidden_services:
      8008: 8008
