# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Development
  name: code-server
  version: 4.5.2
  tagline: Run VS Code on your Citadel
  description: This app doesn't  have a description yet.
  developers:
    Coder: https://coder.com
  dependencies: []
  repo: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - name: server
    image: codercom/code-server:4.5.2@sha256:98c374514bb8560b1005ae8ffa4f5f65a553d2b49f8787e4af76210596b9c7e1
    user: 1000:1000
    port: 8080
    environment:
      PASSWORD: $APP_SEED
    data:
      - data:/home/coder
