citadel_version: 4
metadata:
  category: Media
  name: Piwigo
  version: "13.1.0"
  tagline: Perfect Replacement for Google Photos
  description: >-
    For First time installation, use credentials :


    DB_HOST:db


    DB_USER:piwigo


    DB_PASSWORD:piwigo


    DB_NAME:piwigo

    Manage your photo library. Piwigo is open source photo gallery software for the web. Designed for organisations, teams and individuals.


    Piwigo offers a wide set of features for any photo gallery. Many of the available features are listed below. New features are added to Piwigo on an ongoing basis, because of coding team ideas and discussions with the user community.

    Upload your photos -


    You can add photos with the web form, any FTP client or


    a desktop application like digiKam, Shotwell, Lightroom or


    mobile applications.


    Batch Manager -


    Filter photos from your collection, make a selection and apply actions in batch, change the author, add some tags, associate to a new album, set geolocation...


    Organize and share your photos -


    Organize with Album -


    Distribute your photos among your own albums. The album tree has unlimited depth. Each photo can belong to several albums.


    Browse by Dates -


    Digital cameras store the date in the photo and Piwigo uses this date to display your photo collection in a calendar and let you browse from day to day.


    Privacy on your Photos -


    Make your photos private and decide who can see each of them. You can set permissions on albums and photos, for groups or individual users.


    Geolocate your photos on a map -


    Piwigo can read GPS latitude and longitude from embedded metadata. Then, with plugin for Google Maps or OpenStreetMap, Piwigo can display your photos on an interactive map.


    Themes & Plugins -


    Change appearance with themes. Add features with plugins. Extensions require just a few clicks to get installed. 350 extensions available, and growing!
  developers:
    Piwigo Team: https://piwigo.org/

  repo:
    Public: https://github.com/Piwigo/Piwigo
  support: https://github.com/Piwigo/Piwigo/wiki

  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  path: ""
  defaultUsername: "piwigo"
  defaultPassword: "piwigo"
  torOnly: false

services:
  main:
    image: linuxserver/piwigo:13.1.0@sha256:6dae3dccb7bb4fb2bcdcd6fdfd329713692464c0e8cf2be96eb2b3eba0f96b4a
    restart: on-failure
    links:
      - db
    volumes:
      - data/config:/config
      - data/gallery:/gallery
    port: 80

  db:
    image: mariadb:10.5.12@sha256:f0e9a95a715f5f1233f0513b6ccc83e2d5692cd787bc9425e11cef667cf086ec
    container_name: piwigo-db
    volumes:
      - ./piwigo-db:/var/lib/mysql
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: piwigo
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: piwigo
    restart: on-failure
