version: 3
metadata:
  category: Finance
  name: LN Markets
  version: 2.0.0
  tagline: Trade Bitcoin derivatives on Lightning
  description: "LN Markets is the first Lightning-native Bitcoin derivatives trading platform.\n\nLN Markets enables traders to take minimal counterparty risk:\n  you can trade directly from your Lightning wallet for instant and almost costless transactions.\n  Since March 2020, we have processed over $200 million of trading volume,\n  with a median fee of 1 sat for instant P&L delivery to your wallet.\n\n\n  \n\n\n  \nThis app gives you another way to interact with LN Markets:\n  you can directly deposit, withdraw, get trading stats and get instantly connected to your account to take positions as usual.\n  More features may come in the future!\n\n\nThank you for your support and let's keep building the future of finance together!"
  developers:
    LN Markets: https://lnmarkets.com
  dependencies:
  - lnd
  repo: https://github.com/ln-markets/umbrel
  support: https://www.t.me/lnmarkets
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
containers:
- name: lnmarkets
  image: ghcr.io/ln-markets/umbrel:v1.2.3@sha256:c11ec6d28d1b1d11d82ae8b33916732686a296beb21c9c3eaee80c823bd2d00f
  environment:
    APP_PASSWORD: $APP_SEED
    APP_DOMAIN: $APP_DOMAIN
    API_PORT: 1234
    APP_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE
    LND_REST_PORT: $LND_REST_PORT
    APP_URL: 0.0.0.0
    LND_GRPC_PORT: $LND_GRPC_PORT
    BITCOIN_NETWORK: $BITCOIN_NETWORK
    LND_IP: $LND_IP
  init: true
  port: 1234
  stop_grace_period: 1m
  user: 1000:1000
