# SPDX-FileCopyrightText: 2021-2022 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v4.yml

citadel_version: 4

metadata:
  category: Wallets
  name: JAM
  version: 0.1.0
  tagline: JoinMarket's awesome, man
  description: JAM (JoinMarket's awesome, man) is a web-interface for JoinMarket
    with focus on user-friendliness. It's time for top-notch privacy for your
    bitcoin. Widespread use of JoinMarket improves bitcoin's fungibility and
    privacy for all. The app provides sensible defaults and is easy to use for
    beginners while still providing the features advanced users expect.
  developers:
    JAM developers: https://github.com/joinmarket-webui/jam
  permissions:
    - bitcoind
  repo:
    Public: https://github.com/joinmarket-webui/jam
  support: https://t.me/JoinMarketWebUI
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
    - 4.jpg
    - 5.jpg
  defaultPassword: $APP_SEED

services:
  main:
    image: ghcr.io/joinmarket-webui/jam-standalone:v0.1.0-clientserver-v0.9.8
    restart: on-failure
    stop_grace_period: 1m
    init: true
    port: 80
    mounts:
      data:
        data/joinmarket: /root/.joinmarket
    environment:
      RESTORE_DEFAULT_CONFIG: "true"
      REMOVE_LOCK_FILES: "true"
      ENSURE_WALLET: "true"
      APP_USER: citadel
      APP_PASSWORD: ${APP_SEED}
      jm_rpc_host: $BITCOIN_IP
      jm_rpc_port: $BITCOIN_RPC_PORT
      jm_rpc_user: $BITCOIN_RPC_USER
      jm_rpc_password: ${BITCOIN_RPC_PASS}
      jm_rpc_wallet_file: jm_webui_default
      jm_network: $BITCOIN_NETWORK
      jm_max_cj_fee_abs: "300000"
      jm_max_cj_fee_rel: "0.0003"
