# SPDX-FileCopyrightText: 2021 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Wallets
  name: JAM
  version: 0.0.10
  tagline: JoinMarket's awesome, man
  description: JAM (JoinMarket's awesome, man) is a web-interface for JoinMarket
    with focus on user-friendliness. It's time for top-notch privacy for your
    bitcoin. Widespread use of JoinMarket improves bitcoin's fungibility and
    privacy for all. The app provides sensible defaults and is easy to use for
    beginners while still providing the features advanced users expect.
  developers:
    JAM developers: https://github.com/joinmarket-webui/joinmarket-webui
  dependencies:
    - bitcoind
  repo: https://github.com/joinmarket-webui/joinmarket-webui
  support: https://t.me/JoinMarketWebUI
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
    - 4.jpg
    - 5.jpg
  defaultPassword: $APP_SEED
containers:
  - name: joinmarket-webui
    image: ghcr.io/joinmarket-webui/joinmarket-webui-standalone:v0.0.10-clientserver-v0.9.6
    restart: on-failure
    stop_grace_period: 1m
    init: true
    port: 80
    data:
      - data/joinmarket:/root/.joinmarket
    environment:
      RESTORE_DEFAULT_CONFIG: "true"
      REMOVE_LOCK_FILES: "true"
      ENSURE_WALLET: "true"
      APP_USER: citadel
      APP_PASSWORD: ${APP_SEED}
      jm_tor_control_host: $TOR_PROXY_IP
      jm_tor_control_port: 29051
      jm_onion_socks5_host: $TOR_PROXY_IP
      jm_onion_socks5_port: $TOR_PROXY_PORT
      jm_socks5_host: $TOR_PROXY_IP
      jm_socks5_port: $TOR_PROXY_PORT
      jm_rpc_host: $BITCOIN_IP
      jm_rpc_port: $BITCOIN_RPC_PORT
      jm_rpc_user: $BITCOIN_RPC_USER
      jm_rpc_password: ${BITCOIN_RPC_PASS}
      jm_rpc_wallet_file: jm_webui_default
      jm_network: $BITCOIN_NETWORK
      jm_max_cj_fee_abs: 300000
      jm_max_cj_fee_rel: 0.0003
