citadel_version: 4
metadata:
  name: Kollider
  version: 1.0.6
  category: Finance
  tagline: Lightning-fast derivative trading
  developers:
    Kollider: https://kollider.xyz
  permissions:
  - lnd
  repo:
    Public: https://github.com/kolliderhq/kollider-lite-app
  support: https://t.me/kolliderhq
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED
  torOnly: false
  description: Kollider lets you instantly trade perpetual contracts with low fees and up to 100x buying power. No need to pre-fund a trading account, each trade settles directly from your own wallet or even from your own lightning node in milliseconds. The Kollider App lets you use the Lightning Network to get instant exposure to a range of products using Bitcoin, directly from your node. More features coming soon!
services:
  ws:
    image: kolliderhq/kollider-ws-client:v1.0.6@sha256:05f3d1ddf9949b377788e442a1050457559291a50510f5d6dfa66a28c283a80a
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    init: true
    environment:
      KOLLIDER_ZMQ_PUB_ADDRESS: tcp://*:5556
      KOLLIDER_ZMQ_HEDGER_SUB_ADDRESS: tcp://${APP_KOLLIDER_BACKEND_IP}:5559
      APP_PASSWORD: $APP_SEED
      KOLLIDER_ZMQ_SUB_ADDRESS: tcp://${APP_KOLLIDER_BACKEND_IP}:5557
      KOLLIDER_ZMQ_HEDGER_ADDRESS: tcp://${APP_KOLLIDER_BACKEND_IP}:5558
    required_ports:
      tcp:
        4244: 8080
      udp: null
  web:
    image: kolliderhq/kollider-lite-app:v1.0.6@sha256:f5bbbea86ed4d03c9a7c66527edbcda05228986ba5721e65c08a885edb74151a
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    init: true
    port: 3000
    mounts:
      data:
        data/cache/images: /app/.next/cache/images
  backend:
    image: kolliderhq/kollider-lite-backend:v1.0.6@sha256:5558948e716fe31956ef1e3985aede704b0bcd9b3af2532395c8774cffdf1666
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    init: true
    environment:
      LND_IP: $LND_IP
      LND_ZMQ_SUB_ADDRESS: tcp://${APP_KOLLIDER_WS_IP}:5556
    mounts:
      lnd: /lnd
      data:
        data/logs: /app/logs
