citadel_version: 4
metadata:
  name: LnVisualizer
  version: 0.0.28
  category: Explorers
  tagline: View the Lightning Network from your node's perspective
  developers:
    Max Kotlan: https://lnvisualizer.com
  description: Your Lightning node is continuously receiving, storing, and transmitting graph information. LnVisualizer takes this data and transforms it into an interactive, 3D graph. Search for nodes, filter the graph, and write custom queries to help understand your position in the network.
  permissions:
  - lnd
  repo:
    Public: https://github.com/MaxKotlan/LN-Visualizer
  support: lnvisualizer@gmail.com
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: null
  torOnly: false
  compatible: false
services:
  main:
    image: maxkotlan/ln-visualizer-web:v0.0.28@sha256:d207e2e474453090d8c0ebec568c94536f79c9ae0d691818068861bbc2abb25d
    stop_grace_period: 1m
    restart: on-failure
    environment:
      LN_VISUALIZER_API_URL: http://${APP_LN_VISUALIZER_API_IP}:5647
    port: 80
  api:
    image: maxkotlan/ln-visualizer-api:v0.0.20@sha256:cfea255f3343dbacf96c5470dcd442f1cc034337dfb46ecfbbc6d5c1978da1a4
    user: 1000:1000
    stop_grace_period: 1m
    restart: on-failure
    environment:
      LND_CERT_FILE: /lnd/tls.cert
      LND_SOCKET: ${LND_IP}:${LND_GRPC_PORT}
      LND_MACAROON_FILE: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/readonly.macaroon
    mounts:
      lnd: /lnd
